name: Deploy layer

on:
  push:
    branches:
      - master
      - proj

permissions:
  contents: read
  id-token: write

env:
  PHP_VERSION: "8.2"
  PHP_EXTENSIONS: "curl, dom, simplexml, soap, bcmath, mbstring, zip"

jobs:
  deploy:
    name: Deploy Serverless stack
    runs-on: ubuntu-latest
    environment: eu-central-1
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}

      - uses: ramsey/composer-install@v1
        with:
          composer-options: "--prefer-dist --no-dev --optimize-autoloader --ignore-platform-reqs"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::950438783624:role/GItHubActionsOpenIDCOnnectRole
          role-session-name: ${{ env.DEPLOYMENT_NAME }}-deployer
          aws-region: ${{ env.DEPLOYMENT_REGION }}

      - name: Build layer
        run: make publish
        env:
          layer: proj
          php_versions: 82
          only_region: eu-central-1
